### PR TITLE
Fixed broken project page

### LINKED ISSUE #104: [URGENT] Projects tab broke down
Note sure what happened in recent PRs, but /projects broke down. When I click on it in the menu bar or try to load it from the URL directly, it doesn't work

### PR DESCRIPTION
**Pull request by dhairya-rathod**
This PR closes #104 

The server request must include the query parameter `page` for the **/projects** page. The server request is currently being passed with `page` value as `undefined` which is why it produces an error. In this PR, the problem was fixed by adding the default value of a `page` if it is `undefined`.

Moreover, a safety check for `images` and `description` was added to the `src\components\CrowdActionCard.tsx` component because the page would crash without those values.

image

### CODE REVIEW

**Comment by tomsiebring** [comment]
@dastrong How does it look to you?

File: src/components/NavBar.tsx [hunk 1]
```diff
@@ -170,7 +170,7 @@ export default function NavBar() {
                 {t('app:navbar.team')}
               </Link>
               <Link
-                href="/projects"
+                href="/projects?page=1"
```
Comment (Xazin) [inline src/components/NavBar.tsx:173]: You don't need this with the change insides `projects/index.tsx`

**Review by Xazin — APPROVED** [review]
